# Generated by Django 6.1.1 on 2026-10-01 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, null=True)),
                ('project_description', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='media/project_img')),
                ('status', models.CharField(choices=[('NotStarted', 'NotStarted'), ('Inprogress', 'Inprogress'), ('Completed', 'Completed')], max_length=20, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
